services:
  - type: web
    name: cody-ai
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: OWNER_NUMBER
        sync: false
      - key: OWNER_NAME
        sync: false
      - key: BOT_NAME
        value: Cody AI V2
